jdbc:
  derby:
    url: jdbc:derby:target/demodb;create=true
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    initialSize: 1

cayenne:
  datasource: derby #target database
  createSchema: true

linkmove:
  connectorFactories:
    - type: uri
      connectors: #data sources
        domainSourceConnector: classpath:etl/domain.json
        tagSourceConnector: tag.csv