jdbc:
  sourcedb:
      url: jdbc:mysql://localhost:3306/sourcedb?connectTimeout=0&autoReconnect=true
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 1
      username: root
      password:

cayenne:
  datasource: sourcedb

linkmove:
  extractorsDir: classpath:etl
  connectorFactories:
    - type: uri
      connectors:
        tagSourceConnector: classpath:etl/tag.csv
        articleSourceConnector: classpath:etl/article.csv

